name: Lighthouse

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install LHCI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse
        run: |
          lhci autorun | tee output.txt

      - name: Extract report URL
        run: |
          URL=$(grep -o 'https://storage.googleapis.com[^ ]*' output.txt | head -n 1)
          echo "{\"url\": \"$URL\"}" > latest-report.json

      - name: Commit report link
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add latest-report.json
          git commit -m "Atualiza relatório Lighthouse" || echo "Sem mudanças"
          git push
